# Generated by Django 5.1.7 on 2025-03-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_open', models.DateTimeField(auto_now_add=True, verbose_name='Дата открытия смены')),
                ('active', models.BooleanField(default=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Выручка')),
                ('date_close', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия смены')),
            ],
        ),
    ]
